version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env.development
    networks:
      - next_network
  faunadb:
    image: fauna/faunadb
    networks:
     - next_network
    ports:
      - "8443:8443"
      - "8084:8084"
networks:
  next_network: